#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_generate_one_variable:
  path: /api/generateOneVariable/{numberOfVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataController::execute
  methods: GET
  requirements:
    indicatorId: '\d+'

api_generate_one_variable_joined:
  path: /api/generateOneVariableJoined/{numberOfVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataJoinedController::execute
  methods: GET
  requirements:
    indicatorId: '\d+'

api_read_all_one_variable:
  path: /api/readOneVariable/
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataWithNamesController::execute
  methods: GET

api_read_all_one_variable_joined:
  path: /api/readOneVariableJoined/
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataJoinedWithNamesController::execute
  methods: GET

api_evaluate_one_variable:
  path: /api/evaluate/one-variable/{numberOfAttempts}/
  controller: App\PerformanceSimba\Infrastructure\Controller\EvaluateReadOneVariableDataController:execute
  methods: GET