#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_generate_one_variable:
  path: /api/generateOneVariable/{numVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataController::execute
  methods: GET
  requirements:
    indicatorId: '\d+'

api_read_all_one_variable:
  path: /api/readOneVariable/
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataWithNamesController::execute
  methods: GET