#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_generate_one_variable:
  path: /api/generateOneVariable/{numberOfVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataController::execute
  methods: GET
  requirements:
    numberOfVariables: '\d+'

api_generate_one_variable_joined:
  path: /api/generateOneVariableJoined/{numberOfVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataJoinedController::execute
  methods: GET
  requirements:
    numberOfVariables: '\d+'

api_generate_three_variable_joined:
  path: /api/generateThreeVariableJoined/{offsetVariable}/{numberOfVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForThreeVariableDataJoinedController::execute
  methods: GET
  requirements:
    offsetVariable: '\d+'
    numberOfVariables: '\d+'

api_generate_three_variable:
  path: /api/generateThreeVariable/{offsetVariable}/{numberOfVariables}/
  controller: App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForThreeVariableDataController::execute
  methods: GET
  requirements:
    offsetVariable: '\d+'
    numberOfVariables: '\d+'

api_read_all_one_variable:
  path: /api/readOneVariable/
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataWithNamesController::execute
  methods: GET

api_read_all_one_variable_joined:
  path: /api/readOneVariableJoined/
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataJoinedWithNamesController::execute
  methods: GET

api_read_three_variable_joined_by_id:
  path: /api/readThreeVariableJoinedById/{jsonRequest}
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadThreeVariableDataJoinedByIdWithNamesController::execute
  methods: GET

api_read_three_variable_by_id:
  path: /api/readThreeVariableById/{jsonRequest}
  controller: App\PerformanceSimba\Infrastructure\Controller\ReadThreeVariableDataByIdWithNamesController::execute
  methods: GET

api_evaluate_one_variable:
  path: /api/evaluate/one-variable/{numberOfAttempts}/
  controller: App\PerformanceSimba\Infrastructure\Controller\EvaluateReadOneVariableDataController:execute
  methods: GET
  requirements:
    numberOfAttempts: '\d+'

api_evaluate_three_variable_by_id:
  path: /api/evaluate/three-variable/{numberOfAttempts}/{numberOfRegisters}/{idMinimum}/{idMaximum}
  controller: App\PerformanceSimba\Infrastructure\Controller\EvaluateReadThreeVariableDataByIdController:execute
  methods: GET
  requirements:
    numberOfAttempts: '\d+'
    numberOfRegisters: '\d+'
    idMinimum: '\d+'
    idMaximum: '\d+'

api_evaluate_three_variable_joined_by_id:
  path: /api/evaluate/three-variable-joined/{numberOfAttempts}/{numberOfRegisters}/{idMinimum}/{idMaximum}
  controller: App\PerformanceSimba\Infrastructure\Controller\EvaluateReadThreeVariableDataJoinedByIdController:execute
  methods: GET
  requirements:
    numberOfAttempts: '\d+'
    numberOfRegisters: '\d+'
    idMinimum: '\d+'
    idMaximum: '\d+'

api_evaluate_one_variabl_joined:
  path: /api/evaluate/one-variable-joined/{numberOfAttempts}/
  controller: App\PerformanceSimba\Infrastructure\Controller\EvaluateReadOneVariableDataJoinedController:execute
  methods: GET
  requirements:
    numberOfAttempts: '\d+'

api_empty_database:
  path: /api/emptyDatabase/
  controller: App\PerformanceSimba\Infrastructure\Controller\EmptyDatabaseController:execute
  methods: GET
