# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
#    App\Controller\:
#        resource: '../src/Controller/'
#        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    performanceSimba.repository.metadata.firstVariableDictionary:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\FirstVariableDictionary

    performanceSimba.repository.metadata.secondVariableDictionary:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\SecondVariableDictionary

    performanceSimba.repository.metadata.thirdVariableDictionary:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\ThirdVariableDictionary

    performanceSimba.repository.doctrine.firstVariableDictionary:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineFirstVariableDictionaryRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.firstVariableDictionary"

    performanceSimba.repository.doctrine.secondVariableDictionary:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineSecondVariableDictionaryRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.secondVariableDictionary"

    performanceSimba.repository.doctrine.thirdVariableDictionary:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineThirdVariableDictionaryRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.thirdVariableDictionary"

    performanceSimba.repository.metadata.oneVariableData:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\OneVariableData

    performanceSimba.repository.doctrine.oneVariableData:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineOneVariableDataRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.oneVariableData"

    performanceSimba.useCase.generateValuesForOneVariableData:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\GenerateValuesForOneVariableDataUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.oneVariableData"
            - "@performanceSimba.repository.doctrine.firstVariableDictionary"

    App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.generateValuesForOneVariableData"

    performanceSimba.useCase.readAllOneVariableDataWithNames:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\ReadAllOneVariableDataWithNamesUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.oneVariableData"
            - "@performanceSimba.repository.doctrine.firstVariableDictionary"

    App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataWithNamesController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.readAllOneVariableDataWithNames"

    performanceSimba.repository.metadata.oneVariableDataJoined:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\OneVariableDataJoined

    performanceSimba.repository.metadata.threeVariableDataJoined:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\ThreeVariableDataJoined

    performanceSimba.repository.metadata.threeVariableData:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\ThreeVariableData

    performanceSimba.repository.doctrine.oneVariableDataJoined:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineOneVariableDataJoinedRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.oneVariableDataJoined"

    performanceSimba.repository.doctrine.threeVariableDataJoined:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineThreeVariableDataJoinedRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.threeVariableDataJoined"

    performanceSimba.repository.doctrine.threeVariableData:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineThreeVariableDataRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.threeVariableData"

    performanceSimba.useCase.readAllOneVariableDataJoinedWithNames:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\ReadAllOneVariableDataJoinedWithNamesUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.oneVariableDataJoined"

    performanceSimba.useCase.readThreeVariableDataJoinedByIdWithNames:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\ReadThreeVariableDataJoinedByIdWithNamesUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.threeVariableDataJoined"

    performanceSimba.useCase.readThreeVariableDataByIdWithNames:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\ReadThreeVariableDataByIdWithNamesUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.threeVariableData"
            - "@performanceSimba.repository.doctrine.firstVariableDictionary"
            - "@performanceSimba.repository.doctrine.secondVariableDictionary"
            - "@performanceSimba.repository.doctrine.thirdVariableDictionary"

    performanceSimba.useCase.emptyDatabase:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\EmptyDatabaseUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.oneVariableData"
            - "@performanceSimba.repository.doctrine.threeVariableData"
            - "@performanceSimba.repository.doctrine.firstVariableDictionary"
            - "@performanceSimba.repository.doctrine.secondVariableDictionary"
            - "@performanceSimba.repository.doctrine.thirdVariableDictionary"
            - "@performanceSimba.repository.doctrine.oneVariableDataJoined"
            - "@performanceSimba.repository.doctrine.threeVariableDataJoined"
            - "@performanceSimba.repository.doctrine.firstVariableDictionaryJoined"
            - "@performanceSimba.repository.doctrine.secondVariableDictionaryJoined"
            - "@performanceSimba.repository.doctrine.thirdVariableDictionaryJoined"

    App\PerformanceSimba\Infrastructure\Controller\ReadAllOneVariableDataJoinedWithNamesController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.readAllOneVariableDataJoinedWithNames"

    App\PerformanceSimba\Infrastructure\Controller\ReadThreeVariableDataJoinedByIdWithNamesController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.readThreeVariableDataJoinedByIdWithNames"

    App\PerformanceSimba\Infrastructure\Controller\ReadThreeVariableDataByIdWithNamesController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.readThreeVariableDataByIdWithNames"

    App\PerformanceSimba\Infrastructure\Controller\EmptyDatabaseController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.emptyDatabase"

    performanceSimba.repository.metadata.firstVariableDictionaryJoined:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\FirstVariableDictionaryJoined

    performanceSimba.repository.metadata.secondVariableDictionaryJoined:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\SecondVariableDictionaryJoined

    performanceSimba.repository.metadata.thirdVariableDictionaryJoined:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - App\PerformanceSimba\Domain\DataDictionary\Entity\ThirdVariableDictionaryJoined

    performanceSimba.repository.doctrine.firstVariableDictionaryJoined:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineFirstVariableDictionaryJoinedRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.firstVariableDictionaryJoined"

    performanceSimba.repository.doctrine.secondVariableDictionaryJoined:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineSecondVariableDictionaryJoinedRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.secondVariableDictionaryJoined"

    performanceSimba.repository.doctrine.thirdVariableDictionaryJoined:
        class: App\PerformanceSimba\Infrastructure\Persistence\Repository\DoctrineThirdVariableDictionaryJoinedRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@performanceSimba.repository.metadata.thirdVariableDictionaryJoined"

    performanceSimba.useCase.generateValuesForOneVariableDataJoined:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\GenerateValuesForOneVariableDataJoinedUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.oneVariableDataJoined"
            - "@performanceSimba.repository.doctrine.firstVariableDictionaryJoined"

    performanceSimba.useCase.generateValuesForThreeVariableDataJoined:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\GenerateValuesForThreeVariableDataJoinedUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.threeVariableDataJoined"
            - "@performanceSimba.repository.doctrine.firstVariableDictionaryJoined"
            - "@performanceSimba.repository.doctrine.secondVariableDictionaryJoined"
            - "@performanceSimba.repository.doctrine.thirdVariableDictionaryJoined"

    performanceSimba.useCase.generateValuesForThreeVariableData:
        class: App\PerformanceSimba\Application\DataDictionary\UseCase\GenerateValuesForThreeVariableDataUseCase
        arguments:
            - "@performanceSimba.repository.doctrine.threeVariableData"
            - "@performanceSimba.repository.doctrine.firstVariableDictionary"
            - "@performanceSimba.repository.doctrine.secondVariableDictionary"
            - "@performanceSimba.repository.doctrine.thirdVariableDictionary"

    App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForOneVariableDataJoinedController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.generateValuesForOneVariableDataJoined"

    App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForThreeVariableDataJoinedController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.generateValuesForThreeVariableDataJoined"

    App\PerformanceSimba\Infrastructure\Controller\GenerateValuesForThreeVariableDataController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.generateValuesForThreeVariableData"

    App\PerformanceSimba\Infrastructure\Controller\EvaluateReadOneVariableDataController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.readAllOneVariableDataWithNames"

    App\PerformanceSimba\Infrastructure\Controller\EvaluateReadOneVariableDataJoinedController:
        tags: [ controller.service_arguments ]
        arguments:
            - "@performanceSimba.useCase.readAllOneVariableDataJoinedWithNames"